apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
 name: workload-cluster-name
spec:
  registryMirrorConfiguration:
    endpoint: "harbor-proxycache-csc-ireland.oidc.thecloudgarage.com"
    insecureSkipVerify: true
    port: 443
    ociNamespaces:
      - registry: docker.io
        namespace: proxy.docker.io
      - registry: gcr.io
        namespace: proxy.gcr.io
      - registry: k8s.gcr.io
        namespace: proxy.k8s.gcr.io
      - registry: quay.io
        namespace: proxy.quay.io
      - registry: registry.k8s.io
        namespace: proxy.registry.k8s.io
  clusterNetwork:
    cni: cilium
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 3
    endpoint:
      host: "api-server-ip"
    machineGroupRef:
      kind: VSphereMachineConfig
      name: workload-cluster-name-cp
  datacenterRef:
    kind: VSphereDatacenterConfig
    name: workload-cluster-name-dcconfig
  kubernetesVersion: "1.21"
  managementCluster:
    name: management-cluster-name
  workerNodeGroupConfigurations:
  - count: 2 #Creates a worker node pool named md-0 with a static count, ideal for stateful applications
    machineGroupRef:
      kind: VSphereMachineConfig
      name: workload-cluster-name-md-0
    name: md-0
    labels:
      group: md-0

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereDatacenterConfig
metadata:
  name: workload-cluster-name-dcconfig
spec:
  datacenter: "VxRail-Datacenter"
  insecure: true
  network: "Production_VLAN102"
  server: "mc-mg-vcsa.edub.csc"
  thumbprint: "B0:AE:F4:11:B9:F3:4C:E7:47:02:13:71:96:6D:62:6D:18:EE:F8:A1"

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: workload-cluster-name-cp
spec:
  datastore: "VxRail-Virtual-SAN-Datastore-9cda2d8e-54da-466b-8203-cb97974fa0d7"
  diskGiB: 25
  folder: "eks-anywhere"
  memoryMiB: 8192
  numCPUs: 4
  osFamily: ubuntu
  template: "ubuntu-2004-kube-v1.21"
  resourcePool: "eksa"
  users:
  - name: capv
    sshAuthorizedKeys:
    - ""

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: workload-cluster-name-md-0
spec:
  datastore: "VxRail-Virtual-SAN-Datastore-9cda2d8e-54da-466b-8203-cb97974fa0d7"
  diskGiB: 25
  folder: "eks-anywhere"
  memoryMiB: 8192
  numCPUs: 4
  osFamily: ubuntu
  template: "ubuntu-2004-kube-v1.21"
  resourcePool: "eksa"
  users:
  - name: capv
    sshAuthorizedKeys:
    - ""
