apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim-powerstore-ext4
  namespace: demo
  labels:
    name: mysql-pv-claim-powerstore-ext4
    csi: powerstore-ext4
spec:
  storageClassName: powerstore-topology
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
